### ISSUE TITLE
Is it possible to use SPDY without HTTPS?

### ISSUE THREAD

**Issue by vojtajina** [spdy-http2/node-spdy#103]
If I use `plain: false, ssl: false`, it still only serves on https.
If I use `plain: true, ssl: false`, it seems like regular http.HttpServer, without SPDY (I'm only judging based on the chrome SPDY extension which does not indicate SPDY).

Is is possible to use SPDY with node-spdy without HTTPS ?

**Comment by cusspvz** [comment]
@indutny so what's the configuration for those who have the TLS termination on the load balancer? `plain: false, ssl: false` ?

**Comment by indutny** [comment]
@cusspvz `plain: true, ssl: false`
