### ISSUE TITLE
Explain usage in browsers

### ISSUE THREAD

**Issue by simevidas** [spdy-http2/node-spdy#169]
(Sorry for the n00b question.) I'm not sure that the "Client" code means (in the README). It starts with:

``` js
var spdy = require('spdy');
var http = require('http');
```

Does this mean that I have to load these packages onto the web page in the browser? Like with browserify? Is there a ready-to-use browser script that I could directly load via `<script>` so that I don't have to build it via browserify?

**Comment by Hosar** [comment]
@simevidas  how do you handle the browser request? with a library like superagent?
