### ISSUE TITLE
Bug in spdy-transport/agent code causes writing of frames after receiving GOAWAY

### ISSUE THREAD

**Issue by anandsuresh** [spdy-http2/node-spdy#291]
We're seeing a more than a few of the following exceptions when using node-spdy with Apple's APNS service over HTTP/2.

```
Cannot read property 'writeQueueSize' of null

TypeError: Cannot read property 'writeQueueSize' of null
    at Socket._writeGeneric (net.js:703:32)
    at Socket._write (net.js:716:8)
    at doWrite (_stream_writable.js:300:12)
    at clearBuffer (_stream_writable.js:407:7)
    at Socket.Writable.uncork (_stream_writable.js:237:7)
    at ClientRequest._flushOutput (_http_outgoing.js:673:10)
    at ClientRequest.OutgoingMessage._flush (_http_outgoing.js:647:16)
    at _http_client.js:156:10
    at callSocketMethod (_http_client.js:552:7)
    at ClientRequest.onSocket (_http_client.js:557:7)
```

I have a feeling this is related to the remote server sending back a GOAWAY frame, and the local server attempts to create a new stream/request on the same agent and gets hosed. I'm looking into it now, but wanted to get some input from the community if anyone else is seeing this issue?

**Comment by anandsuresh** [comment]
Additional errors logged show this:

```
prod-nmn13 on prod-2131.voxer.com

This socket has been ended by the other party

Error: This socket has been ended by the other party
    at TLSSocket.writeAfterFIN [as write] (net.js:284:12)
    at Framer.ondata (/voxer/deploy/server/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_readable.js:542:20)
    at emitOne (events.js:77:13)
    at Framer.emit (events.js:169:7)
    at readableAddChunk (/voxer/deploy/server/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_readable.js:213:18)
    at Framer.Readable.push (/voxer/deploy/server/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_readable.js:172:10)
    at Framer.tickSync (/voxer/deploy/server/node_modules/spdy-transport/lib/spdy-transport/protocol/base/scheduler.js:124:18)
    at Framer.dump (/voxer/deploy/server/node_modules/spdy-transport/lib/spdy-transport/protocol/base/scheduler.js:177:8)
    at Connection._onStreamDrain (/voxer/deploy/server/node_modules/spdy-transport/lib/spdy-transport/connection.js:724:16)
    at /voxer/deploy/server/node_modules/spdy-transport/lib/spdy-transport/connection.js:699:14
```

**Comment by anandsuresh** [comment]
Digging into the code, I came across something that might be responsible for this crash. This case is a little hard to reproduce with a test and it only manifests at scale, so I'm going to explain the sequence of events that might lead to the error described in this issue.

`Agent.prototype._createSocket()` calls `Handle.prototype.assignClientRequest()` ([here](https://github.com/indutny/node-spdy/blob/master/lib/spdy/agent.js#L176)), which monkey-patches `OutgoingMessage.prototype._send()` ([here](https://github.com/indutny/node-spdy/blob/master/lib/spdy/handle.js#L136-L162)) to emit `needStream` ([here](https://github.com/indutny/node-spdy/blob/master/lib/spdy/handle.js#L153)), which is being listened for in `Agent.prototype._createSocket()` ([here](https://github.com/indutny/node-spdy/blob/master/lib/spdy/agent.js#L180-L188)), which in-turn creates a new stream and passes it to `Handle.prototype.setStream()` ([here](https://github.com/indutny/node-spdy/blob/master/lib/spdy/agent.js#L186)), which emits the newly-created stream as an argument to the `stream` event ([here](https://github.com/indutny/handle-thing/blob/master/lib/handle.js#L79)).

However, just before `Handle.prototype.assignClientRequest()` monkey-patches the `OutgoingMessage.prototype._send()` method, it has the following code:

```
    // It is very important to leave this here, otherwise it will be executed
    // on a next tick, after `_send` will perform write
    self.getStream(function(stream) {
      stream.send();
    });
```

If I'm reading the code correctly, then it seems that the intent is to have the above event-handler call `stream.send()` to write out a `HEADERS` frame for the new outgoing request,  before the original `req._send()` method is restored and executed ([here](https://github.com/indutny/node-spdy/blob/master/lib/spdy/handle.js#L155-L161)). Furthermore, the call to the monkey-patched `req._send()` from node-core code in `net.js` ([here](https://github.com/nodejs/node/blob/v4.5.0/lib/_http_outgoing.js#L481)) causes the above sequence to execute synchronously on the same tick, which I expect is intended by design.

To recap for clarity, when `net.js` calls the monkey-patched `req._send()` method, it causes the emission of the `needStream` event, whose handler in `Agent.prototype._createSocket()` creates a new stream and passes it to `handle.setStream()`, which in-turn emits the newly created stream as an argument to the `stream` event on the Handle, whose handler (described in the code above) is setup through `Handle.prototype.getStream()` and awaiting that event to fire, in order to write out the `HEADERS` frame for the outgoing request.

While this works fine in the normal case, consider the case when the remote server has sent a `GOAWAY` frame, that the local `Connection` instance has processed and set `state.goaway` to the frame id specified by the `GOAWAY` frame.

With the `GOAWAY` state now setup to end the connection in the near future, a call to the `needStream` handler in `Agent.prototype._createSocket()` would end up calling the `Connection.prototype.reserveStream()` method ([here](https://github.com/indutny/spdy-transport/blob/master/lib/spdy-transport/connection.js#L608-L617)), which queues up an error to fire off on the next tick, but still returns the newly created stream to maintain the API expectation. This newly created stream will propagate as described above and will cause the Stream to execute `stream.send()`, which will write out a `HEADERS` frame for the outgoing request!

```
Stream.prototype.send = function send(callback) {
  var state = this._spdyState;

  if (state.sent) {
    var err = new Error('Stream was already sent');
    process.nextTick(function() {
      if (callback)
        callback(err);
    });
    return;
  }

  // ==============================================
  // CHECK IF THE REMOTE SERVER HAS TOLD US TO GOAWAY!!!
  if (this.connection._isGoaway(this.id))
    return callback();
  // ==============================================

  state.sent = true;
  state.timeout.reset();

```

I am considering adding the above check to the `Stream.prototype.send()` method, but I'm not sure if that would be sufficient to prevent the susequent call to `req._send()` [here](https://github.com/indutny/node-spdy/blob/master/lib/spdy/handle.js#L161).

Perhaps you have a better idea on how to deal with this.

**Comment by modulesio** [comment]
This started happening with me on recent versions of Chrome/Blink. Originally I thought it was a [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=660708#c2), but it might be down to `node-spdy`.

**Comment by modulesio** [comment]
☝️ Yes, that seems to do the trick 👏.

On that PR I get correct loading of the page on the latest Chrome (`Version 54.0.2840.87 (64-bit)`); without it loading just completely aborts.

**Comment by anandsuresh** [comment]
@modulesio Excellent! Now to see how to get this tested and merged, cuz this change seems to break all client-side tests! :(
