### ISSUE TITLE
Stream chunks. Help.

### ISSUE THREAD

**Issue by Hosar** [spdy-http2/node-spdy#299]
First, thank you for this awesome work.

I've been working with node-spdy and it works really fine. Now I want to stream a set of chunks of information. What I'm doing is as follow:
```
// first set the header to transfer chunked
res.set({
        'Content-Type': 'text/plain',
        'Connection': 'Transfer-Encoding',
        'Transfer-Encoding': 'chunked'
      });

// second, write and flush the chunks to the response.
      fromArray.obj(information).pipe(through.obj(function (chunk, enc, cb) {
        
          res.write(JSON.stringify(chunk));
          res.flush();
          cb();        

      })).on('finish', () => {        
        res.end();
      });
```
This works fine, but the request is changing the protocol to http/1.1 (img).
Is there a better way to do the same, but with **http2** ?

Thanks in advance.

![chunks](https://cloud.githubusercontent.com/assets/9598455/21688249/b704f8ae-d331-11e6-8b89-aeeefa9aa815.png)

**Comment by pavel** [comment]
As per HTTP/2 spec some headers are forbidden:

> An HTTP/2.0 request or response MUST NOT include any of the following header fields:
Connection, Host, Keep-Alive, Proxy-Connection, Transfer-Encoding, and Upgrade

This means that for HTTP/2 you won't be able to use
> 'Connection': 'Transfer-Encoding',
> 'Transfer-Encoding': 'chunked'

My personal opinion is that you should not chunk your data manually, HTTP/2 should handle this for you.

**Comment by diasdavid** [comment]
@pavel thank you for answering this one.

@Hosar do you consider your needs fulfilled? Am I good to close this one?

**Comment by Hosar** [comment]
Yeap sure, thank for your help!
