### ISSUE TITLE
Use .pfx file

### ISSUE THREAD

**Issue by preraksola** [spdy-http2/node-spdy#340]
Is there a way that I can use a ".pfx" file instead of ".cer" and ".key"?
I could not find anything related to this in the documentation.

Thank you.

**Comment by danrzeppa** [comment]
As noted towards the bottom of the [readme](https://github.com/spdy-http2/node-spdy#options)

> All options supported by [tls ](http://nodejs.org/docs/latest/api/tls.html#tls.createServer)work with node-spdy.

Which means that instead of using the `cert` and `key` options, you can use the `pfx` and `passphrase` options.
```javascript
var options: {
  pfx: fs.readFileSync(__dirname + '/keys/spdy.pfx'),
  passphrase: 'spdypass'
}
```

**Comment by preraksola** [comment]
Okay, got it.
Thanks 👍
