### ISSUE TITLE
What has changed in 3.4.7 => 4.0.0?

### ISSUE THREAD

**Issue by tkurki** [spdy-http2/node-spdy#352]
A major version change, but the [commit log](https://github.com/spdy-http2/node-spdy/commits/v4.0.0) for 4.0.0 shows only minor stuff, mostly with deps and tests.

Is there something fundamentally different here that I am missing?

**Comment by llaakso** [comment]
It also seems that big/video files download were _disrupted_ by this change - need to revert back to 3.4.7.

**Comment by jacobheun** [comment]
@tkurki The change was to support the latest LTS versions, node 10 in particular. Support for node versions below 6 was dropped, hence the major semver change.

@llaakso do you have a reproducible test case we can look at for this fix?

**Comment by tkurki** [comment]
Thanks. I'm all done here, I think any real issues should be reported separately with sufficient detail.
